from .activations import get_activations


DEFAULT_FIXED_HP = {
    # SCMPrior
    "mix_probs": (0.7, 0.3),
    "informed_mix_probs": (0.9, 0.1),
    "informed_task_family_probs": (0.85, 0.15),
    "informed_normal_block_allocation": (0.72, 0.22, 0.04, 0.01, 0.0, 0.01, 0.0, 0.0, 0.0),
    "informed_normal_block_allocation_ranges": None,
    "informed_normal_block_allocation_min_counts": None,
    "informed_inhibitor_block_allocation": (0.05, 0.08, 0.02, 0.02, 0.0, 0.05, 0.78, 0.0, 0.0),
    "informed_inhibitor_block_allocation_ranges": None,
    "informed_inhibitor_block_allocation_min_counts": None,
    "informed_feature_block_strength": 0.30,
    "informed_interaction_strength": 0.35,
    "informed_history_strength": 0.70,
    "informed_intervention_strength": 0.20,
    "informed_target_family": "generic_corrosion",
    "informed_physical_marginal_prob": 0.0,
    "informed_physical_marginal_profile": "corrosion_broad",
    "epit_material_coef": 0.575,
    "epit_environment_coef": 0.50,
    "epit_interaction_coef": 0.775,
    "pitting_material_dirichlet_prob": 0.0,
    "pitting_material_dirichlet_concentration": 1.0,
    "pitting_material_dirichlet_active_prob": 0.45,
    "pitting_process_role": None,
    "pitting_process_category_count": None,
    "inhibitor_descriptor_coef": 0.65,
    "inhibitor_context_coef": 0.14,
    "inhibitor_environment_interaction_coef": 0.365,
    "inhibitor_material_interaction_coef": 0.24,
    "inhibitor_intervention_coef": 0.375,
    "inhibitor_descriptor_coef_scale": 1.0,
    "inhibitor_context_coef_scale": 1.0,
    "inhibitor_environment_interaction_coef_scale": 1.0,
    "inhibitor_material_interaction_coef_scale": 1.0,
    "inhibitor_intervention_coef_scale": 1.0,
    # TreeSCM
    "tree_model": "xgboost",
    "tree_depth_lambda": 0.5,
    "tree_n_estimators_lambda": 0.5,
    # Reg2Cls
    "balanced": False,
    "multiclass_ordered_prob": 0.0,
    "cat_prob": 0.2,
    "max_categories": float("inf"),
    "scale_by_max_features": False,
    "permute_features": True,
    "permute_labels": True,
}

DEFAULT_SAMPLED_HP = {
    # Reg2Cls
    "multiclass_type": {"distribution": "meta_choice", "choice_values": ["value", "rank"]},
    # MLPSCM
    "mlp_activations": {
        "distribution": "meta_choice_mixed",
        "choice_values": get_activations(random=True, scale=True, diverse=True),
    },
    "block_wise_dropout": {"distribution": "meta_choice", "choice_values": [True, False]},
    "mlp_dropout_prob": {"distribution": "meta_beta", "scale": 0.9, "min": 0.1, "max": 5.0},
    # MLPSCM and TreeSCM
    "is_causal": {"distribution": "meta_choice", "choice_values": [True, False]},
    "num_causes": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 12,
        "min_mean": 1,
        "round": True,
        "lower_bound": 1,
    },
    "y_is_effect": {"distribution": "meta_choice", "choice_values": [True, False]},
    "in_clique": {"distribution": "meta_choice", "choice_values": [True, False]},
    "sort_features": {"distribution": "meta_choice", "choice_values": [True, False]},
    "num_layers": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 6,
        "min_mean": 1,
        "round": True,
        "lower_bound": 2,
    },
    "hidden_dim": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 130,
        "min_mean": 5,
        "round": True,
        "lower_bound": 4,
    },
    "init_std": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 10.0,
        "min_mean": 0.01,
        "round": False,
        "lower_bound": 0.0,
    },
    "noise_std": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 0.3,
        "min_mean": 0.0001,
        "round": False,
        "lower_bound": 0.0,
    },
    "sampling": {"distribution": "meta_choice", "choice_values": ["normal", "mixed", "uniform"]},
    "pre_sample_cause_stats": {"distribution": "meta_choice", "choice_values": [True, False]},
    "pre_sample_noise_std": {"distribution": "meta_choice", "choice_values": [True, False]},
}
