python -m tabicl.train.run \
  --wandb_log False \
  --wandb_mode disabled \
  --device cuda \
  --prior_device cpu \
  --amp False \
  --max_steps 2 \
  --batch_size 4 \
  --micro_batch_size 2 \
  --batch_size_per_gp 1 \
  --min_features 2 \
  --max_features 8 \
  --max_classes 0 \
  --num_quantiles 99 \
  --min_seq_len 32 \
  --max_seq_len 64 \
  --min_train_size 0.5 \
  --max_train_size 0.5 \
  --prior_type mix_scm \
  --embed_dim 32 \
  --col_num_blocks 1 \
  --row_num_blocks 1 \
  --icl_num_blocks 2 \
  --col_num_inds 16 \
  --checkpoint_dir smoke_test_run \
  --save_temp_every 1 \
  --save_perm_every 1000
